/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**dllExport.tlt
*********************************************************************/
 
#pragma once
 
#ifdef WIN32
#  ifndef DT_OCEAN2020FOM_COMMCE_STATIC
#     ifdef OCEAN2020FOM_COMMCE_EXPORTS
#        define DT_DLL_OCEAN2020FOM_COMMCE __declspec ( dllexport )
#     else
#        define DT_DLL_OCEAN2020FOM_COMMCE __declspec ( dllimport )
#     endif
#  else
#     define DT_DLL_OCEAN2020FOM_COMMCE
#  endif
#else
#  define DT_DLL_OCEAN2020FOM_COMMCE
#endif
