/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hrefListHeader.tlt
*********************************************************************/
 
//! \file reflectedTxRxLink_objListHLA.h
//! \brief Contains the DtReflectedOCEAN2020FOMTxRxLink_objList class declaration.
//! \ingroup OCEAN2020FOM_COMMCE
 
#pragma once
 
#if DtHLA
 
#include "dllExport.h"
#include <vl/reflectedObjectListHLA.h>
#include "reflectedTxRxLink_objHLA.h"
 
namespace OCEAN2020 {
 
//! Instances of DtReflectedOCEAN2020FOMTxRxLink_objList manage a list of
//! DtReflectedOCEAN2020FOMTxRxLink_obj objects.
//! \ingroup OCEAN2020FOM_COMMCE
class DT_DLL_OCEAN2020FOM_COMMCE DtReflectedOCEAN2020FOMTxRxLink_objList : public DtReflectedObjectList
{
public:
   //! Constructor. 
   DtReflectedOCEAN2020FOMTxRxLink_objList(DtExerciseConn* exConn,
      const DtDDMRegionSet* regionSetToUse = 0);
 
   //! Constructor - only subscribe to the RTI::ObjectClassHandles
   //! in handleList.
   DtReflectedOCEAN2020FOMTxRxLink_objList(DtExerciseConn* exConn,
      const DtList *handleList, const DtDDMRegionSet* regionSetToUse = 0);
 
   //! Destructor.
   virtual ~DtReflectedOCEAN2020FOMTxRxLink_objList();
 
private:
 
   //! Copy constructor not implemented - cannot be copied.
   DtReflectedOCEAN2020FOMTxRxLink_objList(const DtReflectedOCEAN2020FOMTxRxLink_objList& orig);
 
   //! Assignment operator not implemented - cannot be copied.
   DtReflectedOCEAN2020FOMTxRxLink_objList& operator=(const DtReflectedOCEAN2020FOMTxRxLink_objList&orig);
 
public:
 
   //! Look up by identifier.
   virtual DtReflectedOCEAN2020FOMTxRxLink_obj* lookup(
#if DtHLA_1516
      RTI::ObjectInstanceHandle id);
#else
      RTI::ObjectHandle id);
#endif
 
   //! Look up by name.
   virtual DtReflectedOCEAN2020FOMTxRxLink_obj* lookup(
      const DtGlobalObjectDesignator& objName);
 
   //! Get the first reflected object in the list.
   virtual DtReflectedOCEAN2020FOMTxRxLink_obj* first() const;
 
   //! Get the last reflected object in the list.
   virtual DtReflectedOCEAN2020FOMTxRxLink_obj* last() const;
 
   //! TxRxLink_obj added callback registration
   virtual void addTxRxLink_objAdditionCallback(
      DtOCEAN2020FOMTxRxLink_objCallbackFunction cb, void* userData);
 
   //! TxRxLink_obj added callback deregistration
   virtual void removeTxRxLink_objAdditionCallback(
      DtOCEAN2020FOMTxRxLink_objCallbackFunction cb, void* userData);
 
   //! TxRxLink_obj removed callback registration
   virtual void addTxRxLink_objRemovalCallback(
      DtOCEAN2020FOMTxRxLink_objCallbackFunction cb, void* userData);
 
   //! TxRxLink_obj removed callback deregistration
   virtual void removeTxRxLink_objRemovalCallback(
      DtOCEAN2020FOMTxRxLink_objCallbackFunction cb, void* userData);
 
protected:
 
   //! Override of virtual function.  Here, we create a DtReflectedOCEAN2020FOMTxRxLink_obj
   virtual DtReflectedObject* newReflectedObject(DtHlaObject* obj) const;
 
   //! Called from processDiscoverObject() after a remote TxRxLink_obj has
   //! been added to the list.  Default implementation prints a message.
   //! Subclasses can override this function to add functionality on
   //! addition.  obj will be an instance of a class derived from DtReflectedObj.
   virtual void objectAdded(DtReflectedObject* obj);
 
};
 
} //end OCEAN2020
 
#endif
