/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hpubHeader.tlt
*********************************************************************/
 
//! \file txRxLink_objPublisherHLA.h
//! \brief Contains the DtOCEAN2020FOMTxRxLink_objPublisher class declaration.
//! \ingroup OCEAN2020FOM_COMMCE
 
#pragma once
 
#if DtHLA
 
#include <vl/objectPublisherHLA.h>
#include "dllExport.h"
 
namespace OCEAN2020 {
 
class DtOCEAN2020FOMTxRxLink_objStateRepository;
 
//! Instances of DtOCEAN2020FOMTxRxLink_objPublisher publish
//! TxRxLink_obj objects to
//! the network.
//! \ingroup OCEAN2020FOM_COMMCE
class DT_DLL_OCEAN2020FOM_COMMCE DtOCEAN2020FOMTxRxLink_objPublisher : public DtObjectPublisher
{
public:
   //! Function prototype for a function that creates a DtOCEAN2020FOMTxRxLink_objStateRepository
   typedef DtOCEAN2020FOMTxRxLink_objStateRepository* (*DtStateRepCreator)();
 
public:
   //! Constructor.
   DtOCEAN2020FOMTxRxLink_objPublisher(
      DtOCEAN2020FOMTxRxLink_objStateRepository* stateRepToUse,
      DtExerciseConn* conn,
      const char* name = 0,
      const DtDDMRegionSet* regionSetToUse = 0);
 
   //! Constructor.
   DtOCEAN2020FOMTxRxLink_objPublisher(
      RTI::ObjectClassHandle h,
      DtExerciseConn* conn,
      const char* name = 0,
      const DtDDMRegionSet* regionSetToUse = 0);
 
   //! Constructor.
   DtOCEAN2020FOMTxRxLink_objPublisher(
      DtExerciseConn* conn,
      const char* name = 0,
      const DtDDMRegionSet* regionSetToUse = 0);
 
   //! Constructor that creates a publisher for an existing DtHlaObject.
   //! (DtHlaObjectWithStateRep is derived from DtHlaObject.)  Typically used
   //! in conjunction with ownership management, when you want to take
   //! ownership and begin updating some attributes of an object that you have
   //! already discovered.
   DtOCEAN2020FOMTxRxLink_objPublisher( DtHlaObjectWithStateRep* obj, DtExerciseConn* conn);
 
   //! The Object class name (TxRxLink_obj)
   static const char * objectClassName();
   
   //! Destructor.
   virtual ~DtOCEAN2020FOMTxRxLink_objPublisher();
 
private:
   //! Copy Constructor -- not implemented.
   DtOCEAN2020FOMTxRxLink_objPublisher(const DtOCEAN2020FOMTxRxLink_objPublisher& orig);
 
   //! Assignment operator -- not implemented.
   DtOCEAN2020FOMTxRxLink_objPublisher& operator=(
      const DtOCEAN2020FOMTxRxLink_objPublisher& orig);
 
public:
 
   //! Returns a pointer to the DtOCEAN2020FOMTxRxLink_objStateRepository - through
   //! which you can set or inspect current state information.
   virtual DtOCEAN2020FOMTxRxLink_objStateRepository* txRxLink_objStateRep();
 
   //! Synonym for txRxLink_objStateRep().
   virtual DtOCEAN2020FOMTxRxLink_objStateRepository* tsr();
 
public:
   //! Give us a function to be used for creating SRs.
   static DtStateRepCreator setStateRepCreator(DtStateRepCreator creator);
 
protected:
   static DtStateRepCreator theStateRepCreator;
};
 
inline DtOCEAN2020FOMTxRxLink_objStateRepository* DtOCEAN2020FOMTxRxLink_objPublisher::txRxLink_objStateRep()
{
   return (DtOCEAN2020FOMTxRxLink_objStateRepository*) myStateRep;
}
 
inline DtOCEAN2020FOMTxRxLink_objStateRepository* DtOCEAN2020FOMTxRxLink_objPublisher::tsr()
{
   return (DtOCEAN2020FOMTxRxLink_objStateRepository*) myStateRep;
}
 
} //end OCEAN2020
 
#endif
