/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hintEncHeader.tlt
*********************************************************************/
 
//! \file txRx_Link_OffReqInterEncoderHLA.h
//! \brief This file provides a declaration of the class
//! DtOCEAN2020FOMTxRx_Link_OffReqInterEncoder.
 
#pragma once
 
#if DtHLA 
 
#include <vl/interactionEncoder.h>
#include "dllExport.h"
 
namespace OCEAN2020 {
 
class DtOCEAN2020FOMTxRx_Link_OffReqInter;
 
//! Instances of DtOCEAN2020FOMTxRx_Link_OffReqInterEncoder are used to encode
//! data from DtOCEAN2020FOMTxRx_Link_OffReqInter objects into
//! network structures.
//! \ingroup OCEAN2020FOM_COMMCE
class DT_DLL_OCEAN2020FOM_COMMCE DtOCEAN2020FOMTxRx_Link_OffReqInterEncoder : public DtInteractionEncoder
{
public:
   //! Constructor.
   DtOCEAN2020FOMTxRx_Link_OffReqInterEncoder(DtExerciseConn* exConn,
      DtInterClassDesc* classDesc);
 
   //! Destructor.
   virtual ~DtOCEAN2020FOMTxRx_Link_OffReqInterEncoder();
 
   //! Copy constructor.
   DtOCEAN2020FOMTxRx_Link_OffReqInterEncoder(const DtOCEAN2020FOMTxRx_Link_OffReqInterEncoder& orig);
 
   //! Assignment operator.
   DtOCEAN2020FOMTxRx_Link_OffReqInterEncoder& operator=(const DtOCEAN2020FOMTxRx_Link_OffReqInterEncoder& orig);
 
protected:

   //! Encodes Rx_HostObjectID from inter into params.
   static void encodeRx_HostObjectID(
      const DtOCEAN2020FOMTxRx_Link_OffReqInter& inter,
      RTI::ParameterHandleValuePairSet* params,
      RTI::ParameterHandle paramHandle);

   //! Encodes Tx_HostObjectID from inter into params.
   static void encodeTx_HostObjectID(
      const DtOCEAN2020FOMTxRx_Link_OffReqInter& inter,
      RTI::ParameterHandleValuePairSet* params,
      RTI::ParameterHandle paramHandle);

};
 
} //end OCEAN2020
 
#endif
