/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hintDecHeader.tlt
*********************************************************************/
 
//! \file txRx_Link_OnReqInterDecoderHLA.h
//! \brief Contains the DtOCEAN2020FOMTxRx_Link_OnReqInterDecoder class declaration.
//! \ingroup OCEAN2020FOM_COMMCE
 
#pragma once
 
#if DtHLA 
 
#include <vl/interactionDecoder.h>
#include "dllExport.h"
 
namespace OCEAN2020 {
 
class DtOCEAN2020FOMTxRx_Link_OnReqInter;
 
//! Instances of DtOCEAN2020FOMTxRx_Link_OnReqInterDecoder are used to decode
//! data from the network into DtOCEAN2020FOMTxRx_Link_OnReqInter
//! objects.
//! \ingroup OCEAN2020FOM_COMMCE
class DT_DLL_OCEAN2020FOM_COMMCE DtOCEAN2020FOMTxRx_Link_OnReqInterDecoder : public DtInteractionDecoder
{
public:
   //! Constructor.
   DtOCEAN2020FOMTxRx_Link_OnReqInterDecoder(DtExerciseConn* exConn,
      DtInterClassDesc* classDesc);
 
   //! Destructor.
   virtual ~DtOCEAN2020FOMTxRx_Link_OnReqInterDecoder();
 
   //! Copy constructor.
   DtOCEAN2020FOMTxRx_Link_OnReqInterDecoder(const DtOCEAN2020FOMTxRx_Link_OnReqInterDecoder& orig);
 
   //! Assignment operator.
   DtOCEAN2020FOMTxRx_Link_OnReqInterDecoder& operator=(const DtOCEAN2020FOMTxRx_Link_OnReqInterDecoder& orig);
 
protected:

   //! Decodes FrequencyHopping from params into inter.
   static void decodeFrequencyHopping(
      DtOCEAN2020FOMTxRx_Link_OnReqInter* inter,
      const RTI::ParameterHandleValuePairSet& params,
      int pairSetIndex);

   //! Decodes Rx_HostObjectID from params into inter.
   static void decodeRx_HostObjectID(
      DtOCEAN2020FOMTxRx_Link_OnReqInter* inter,
      const RTI::ParameterHandleValuePairSet& params,
      int pairSetIndex);

   //! Decodes Tx_HostObjectID from params into inter.
   static void decodeTx_HostObjectID(
      DtOCEAN2020FOMTxRx_Link_OnReqInter* inter,
      const RTI::ParameterHandleValuePairSet& params,
      int pairSetIndex);

};
 
} //end OCEAN2020
 
#endif
