/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**enums.tlt
*********************************************************************/
 
#pragma once
 

enum DtAntennaPatternTypeEnum32
{
   DtAntennaPatternTypeEnum32_OmniDirectional = 0,
   DtAntennaPatternTypeEnum32_Beam = 1,
   DtAntennaPatternTypeEnum32_SphericalHarmonic = 2,
   DtMaxDtAntennaPatternTypeEnum32
};
 

enum DtReferenceSystemEnum8
{
   DtReferenceSystemEnum8_WorldCoordinates = 1,
   DtReferenceSystemEnum8_EntityCoordinates = 2,
   DtMaxDtReferenceSystemEnum8
};
 

enum DtTxRxTypeEnum
{
   DtTxRxTypeEnum_AMCOMM = 0,
   DtTxRxTypeEnum_AMVOICE = 1,
   DtTxRxTypeEnum_CWRADAR = 2,
   DtTxRxTypeEnum_PULSERADAR = 3,
   DtTxRxTypeEnum_QAM = 4,
   DtTxRxTypeEnum_PSK = 5,
   DtTxRxTypeEnum_DSSS = 6,
   DtTxRxTypeEnum_FHSS = 7,
   DtTxRxTypeEnum_JAMMER = 8,
   DtTxRxTypeEnum_JAMMER_FHSS = 9,
   DtTxRxTypeEnum_FM = 10,
   DtTxRxTypeEnum_ASK = 11,
   DtTxRxTypeEnum_NOEPM = 12,
   DtMaxDtTxRxTypeEnum
};
 

enum DtAntiJammingTechniqueEnum
{
   DtAntiJammingTechniqueEnum_DSSS = 0,
   DtAntiJammingTechniqueEnum_FHSS = 1,
   DtAntiJammingTechniqueEnum_Tech3 = 2,
   DtMaxDtAntiJammingTechniqueEnum
};
 

