/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**defineHLAfixedArrayHeader.tlt
*********************************************************************/

#pragma once

#include "../dllExportOCEAN2020FOM_SISOSTD00112015.h"
#include "OCEAN2020FOM_SISOSTD00112015Enums.h"
#include <vlutil/vlMachineTypes.h>
#include <matrix/vlVector.h>
#include <vl/globalObjectDesignator.h>
#include <vlpi/entityType.h>
#include <vlpi/entityIdentifier.h>
#include <vlutil/vlString.h>
#include <vector>
namespace OCEAN2020 {

//! \class  DtOCEAN2020FOMTxSpuriousLeveldBArray
//! \ingroup OCEAN2020FOM_SISOSTD00112015
class DT_DLL_OCEAN2020FOM_SISOSTD00112015 DtOCEAN2020FOMTxSpuriousLeveldBArray
{
public:
   DtOCEAN2020FOMTxSpuriousLeveldBArray();
   ~DtOCEAN2020FOMTxSpuriousLeveldBArray();
   DtOCEAN2020FOMTxSpuriousLeveldBArray(const DtOCEAN2020FOMTxSpuriousLeveldBArray& orig);
   DtOCEAN2020FOMTxSpuriousLeveldBArray& operator=(const DtOCEAN2020FOMTxSpuriousLeveldBArray& orig);


   virtual void setTxSpuriousLeveldBArrayItem(int index, DtFloat32& val);
   virtual void setTxSpuriousLeveldBArray(const DtFloat32 val[3]);

   virtual const DtFloat32* txSpuriousLeveldBArrayItem(int index) const;
   virtual const DtFloat32* txSpuriousLeveldBArray() const;
   
   bool operator==(const DtOCEAN2020FOMTxSpuriousLeveldBArray& other) const;
   bool operator!=(const DtOCEAN2020FOMTxSpuriousLeveldBArray& other) const;
   
   int netSize() const;
   static int octetBoundary();
   unsigned int getPaddingSize(unsigned int byteOffset, unsigned int boundary) const;

   void writeToBuffer( char* buffer ) const;
   void fillFromBuffer( const char* buffer, int bufferSize, int offset );

   virtual void printData() const;

   virtual void printDataToStream(std::ostream &) const;
   
protected:

    DtFloat32 myTxSpuriousLeveldBArray[3];
};

DT_DLL_OCEAN2020FOM_SISOSTD00112015 std::ostream& operator<<(std::ostream& stream, const DtOCEAN2020FOMTxSpuriousLeveldBArray&);
} //end OCEAN2020
