/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**fixedRecordsHeader.tlt
*********************************************************************/
 
#pragma once
 
#include "../dllExportOCEAN2020FOM_SISOSTD00112015.h"
#include "OCEAN2020FOM_SISOSTD00112015Enums.h"
#include <vlutil/vlMachineTypes.h>
#include <vlutil/vlString.h>
#include <vl/globalObjectDesignator.h>
#include <vlpi/entityType.h>
#include <vlpi/entityIdentifier.h>
#include <matrix/vlVector.h>
#include <vector>
 
#include "OCEAN2020FOMCoefficientsLengthlessArray1Plus.h"
#include "OCEAN2020FOMOctetArray3.h"
 namespace OCEAN2020 {
 
//! \class  DtOCEAN2020FOMSphericalHarmonicAntennaStruct
 
//! \ingroup OCEAN2020FOM_SISOSTD00112015
class DT_DLL_OCEAN2020FOM_SISOSTD00112015 DtOCEAN2020FOMSphericalHarmonicAntennaStruct
{
public:
   DtOCEAN2020FOMSphericalHarmonicAntennaStruct();
   ~DtOCEAN2020FOMSphericalHarmonicAntennaStruct();
   DtOCEAN2020FOMSphericalHarmonicAntennaStruct(const DtOCEAN2020FOMSphericalHarmonicAntennaStruct& orig);
   DtOCEAN2020FOMSphericalHarmonicAntennaStruct& operator=(const DtOCEAN2020FOMSphericalHarmonicAntennaStruct& orig);

   virtual void setOrder(const DtU32& val);
   virtual const DtU32& order() const;
   virtual void setCoefficients(const DtOCEAN2020FOMCoefficientsLengthlessArray1Plus& val);
   virtual const DtOCEAN2020FOMCoefficientsLengthlessArray1Plus& coefficients() const;
   virtual void setReferenceSystem(const DtU8& val);
   virtual const DtU8& referenceSystem() const;
   virtual void setPadding(const DtOCEAN2020FOMOctetArray3& val);
   virtual const DtOCEAN2020FOMOctetArray3& padding() const;
 
   bool operator==(const DtOCEAN2020FOMSphericalHarmonicAntennaStruct& other) const;
   bool operator!=(const DtOCEAN2020FOMSphericalHarmonicAntennaStruct& other) const;
 
   int netSize() const;
   static int octetBoundary();
   unsigned int getPaddingSize(unsigned int byteOffset, unsigned int boundary) const;
 
   void writeToBuffer( char* buffer ) const;
   void fillFromBuffer( const char* buffer, int bufferSize, int offset );
 
   virtual void printData() const;
   virtual void printDataToStream(std::ostream &) const;
 
protected:
 
   DtU32 myOrder;
   DtOCEAN2020FOMCoefficientsLengthlessArray1Plus myCoefficients;
   DtU8 myReferenceSystem;
   DtOCEAN2020FOMOctetArray3 myPadding;
};
 
DT_DLL_OCEAN2020FOM_SISOSTD00112015 std::ostream& operator<<(std::ostream& stream, const DtOCEAN2020FOMSphericalHarmonicAntennaStruct&);

} //end OCEAN2020
