/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hpubHeader.tlt
*********************************************************************/
 
//! \file airColumnPublisherHLA.h
//! \brief Contains the DtOCEAN2020FOMAirColumnPublisher class declaration.
//! \ingroup OCEAN2020FOM_Environmental
 
#pragma once
 
#if DtHLA
 
#include <vl/objectPublisherHLA.h>
#include "dllExport.h"
 
namespace OCEAN2020 {
 
class DtOCEAN2020FOMAirColumnStateRepository;
 
//! Instances of DtOCEAN2020FOMAirColumnPublisher publish
//! VS_Environment.AirColumn objects to
//! the network.
//! \ingroup OCEAN2020FOM_Environmental
class DT_DLL_OCEAN2020FOM_ENVIRONMENTAL DtOCEAN2020FOMAirColumnPublisher : public DtObjectPublisher
{
public:
   //! Function prototype for a function that creates a DtOCEAN2020FOMAirColumnStateRepository
   typedef DtOCEAN2020FOMAirColumnStateRepository* (*DtStateRepCreator)();
 
public:
   //! Constructor.
   DtOCEAN2020FOMAirColumnPublisher(
      DtOCEAN2020FOMAirColumnStateRepository* stateRepToUse,
      DtExerciseConn* conn,
      const char* name = 0,
      const DtDDMRegionSet* regionSetToUse = 0);
 
   //! Constructor.
   DtOCEAN2020FOMAirColumnPublisher(
      RTI::ObjectClassHandle h,
      DtExerciseConn* conn,
      const char* name = 0,
      const DtDDMRegionSet* regionSetToUse = 0);
 
   //! Constructor.
   DtOCEAN2020FOMAirColumnPublisher(
      DtExerciseConn* conn,
      const char* name = 0,
      const DtDDMRegionSet* regionSetToUse = 0);
 
   //! Constructor that creates a publisher for an existing DtHlaObject.
   //! (DtHlaObjectWithStateRep is derived from DtHlaObject.)  Typically used
   //! in conjunction with ownership management, when you want to take
   //! ownership and begin updating some attributes of an object that you have
   //! already discovered.
   DtOCEAN2020FOMAirColumnPublisher( DtHlaObjectWithStateRep* obj, DtExerciseConn* conn);
 
   //! The Object class name (VS_Environment.AirColumn)
   static const char * objectClassName();
   
   //! Destructor.
   virtual ~DtOCEAN2020FOMAirColumnPublisher();
 
private:
   //! Copy Constructor -- not implemented.
   DtOCEAN2020FOMAirColumnPublisher(const DtOCEAN2020FOMAirColumnPublisher& orig);
 
   //! Assignment operator -- not implemented.
   DtOCEAN2020FOMAirColumnPublisher& operator=(
      const DtOCEAN2020FOMAirColumnPublisher& orig);
 
public:
 
   //! Returns a pointer to the DtOCEAN2020FOMAirColumnStateRepository - through
   //! which you can set or inspect current state information.
   virtual DtOCEAN2020FOMAirColumnStateRepository* airColumnStateRep();
 
   //! Synonym for airColumnStateRep().
   virtual DtOCEAN2020FOMAirColumnStateRepository* asr();
 
public:
   //! Give us a function to be used for creating SRs.
   static DtStateRepCreator setStateRepCreator(DtStateRepCreator creator);
 
protected:
   static DtStateRepCreator theStateRepCreator;
};
 
inline DtOCEAN2020FOMAirColumnStateRepository* DtOCEAN2020FOMAirColumnPublisher::airColumnStateRep()
{
   return (DtOCEAN2020FOMAirColumnStateRepository*) myStateRep;
}
 
inline DtOCEAN2020FOMAirColumnStateRepository* DtOCEAN2020FOMAirColumnPublisher::asr()
{
   return (DtOCEAN2020FOMAirColumnStateRepository*) myStateRep;
}
 
} //end OCEAN2020
 
#endif
