/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hobjEncHeader.tlt
*********************************************************************/
 
//! \file bathymetryEncoderHLA.h
//! \brief Contains the DtOCEAN2020FOMBathymetryEncoder class declaration.
 
#pragma once
 
#if DtHLA
 
#include "VS_EnvironmentEncoderHLA.h"
#include "dllExport.h"
 
namespace OCEAN2020 {
 
class DtOCEAN2020FOMBathymetryStateRepository;
 
//! Instances of DtOCEAN2020FOMBathymetryEncoder encode data
//! from DtOCEAN2020FOMBathymetryStateRepository objects to the net
//! structures to be sent to the network.
//! \ingroup OCEAN2020FOM_Environmental
class DT_DLL_OCEAN2020FOM_ENVIRONMENTAL DtOCEAN2020FOMBathymetryEncoder : public DtOCEAN2020FOMVS_EnvironmentEncoder
{
public:
 
   //! Default constructor.
   DtOCEAN2020FOMBathymetryEncoder(
      DtExerciseConn* exConn,
      DtObjClassDesc* classDesc);
 
   //! Destructor.
   virtual ~DtOCEAN2020FOMBathymetryEncoder();
 
   //! Copy constructor.
   DtOCEAN2020FOMBathymetryEncoder(const DtOCEAN2020FOMBathymetryEncoder& orig);
 
   //! Assignment operator.
   DtOCEAN2020FOMBathymetryEncoder& operator=(const DtOCEAN2020FOMBathymetryEncoder& orig);
 
public:
   //! Function that creates a DtOCEAN2020FOMBathymetryEncoder.
   static DtHlaStateEncoder* create(
      DtExerciseConn* exConn,
      DtObjClassDesc* classDesc);
   
protected:

   //! Return true if DepthValues needs to be sent
   //! to the network, false otherwise.
   static bool needDepthValues(
      const DtOCEAN2020FOMBathymetryStateRepository& stateRep, 
      const DtOCEAN2020FOMBathymetryStateRepository& asSeenByRemote);
 
   //! Encodes DepthValues from rep into attrs.
   static void encodeDepthValues(
      const DtOCEAN2020FOMBathymetryStateRepository& rep,
      RTI::AttributeHandleValuePairSet* attrs,
      RTI::AttributeHandle attrHandle);

};
 
} //end OCEAN2020
 
#endif
