/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hobjDecHeader.tlt
*********************************************************************/
 
//! \file bathymetryDecoderHLA.h
//! \brief Contains the DtOCEAN2020FOMBathymetryDecoder class declaration.
//! \ingroup OCEAN2020FOM_Environmental
 
#pragma once
 
#if DtHLA 
 
#include "VS_EnvironmentDecoderHLA.h"
#include "dllExport.h"
 
namespace OCEAN2020 {
 
class DtOCEAN2020FOMBathymetryStateRepository;
 
//! Instances of DtOCEAN2020FOMBathymetryDecoder are used to decode
//! data from the network into DtOCEAN2020FOMBathymetryStateRepository objects.
//! \ingroup OCEAN2020FOM_Environmental
class DT_DLL_OCEAN2020FOM_ENVIRONMENTAL DtOCEAN2020FOMBathymetryDecoder : public DtOCEAN2020FOMVS_EnvironmentDecoder
{
public:
   //! Default constructor.
   DtOCEAN2020FOMBathymetryDecoder(
      DtExerciseConn* exConn,
      DtObjClassDesc* classDesc);
 
   //! Destructor.
   virtual ~DtOCEAN2020FOMBathymetryDecoder();
 
   //! Copy constructor.
   DtOCEAN2020FOMBathymetryDecoder(const DtOCEAN2020FOMBathymetryDecoder& orig);
 
   //! Assignment operator.
   DtOCEAN2020FOMBathymetryDecoder& operator=(const DtOCEAN2020FOMBathymetryDecoder& orig);
 
public:
   //! Creates an instance of DtOCEAN2020FOMBathymetryDecoder.
   static DtHlaStateDecoder* create(
      DtExerciseConn* exConn,
      DtObjClassDesc* classDesc);
 
protected:
   
//! Decodes DepthValues from attrs into rep.
   static void decodeDepthValues(
      DtOCEAN2020FOMBathymetryStateRepository* rep,
      const RTI::AttributeHandleValuePairSet& attrs,
      int pairSetIndex);

};
 
} //end OCEAN2020
 
#endif
