/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hpubHeader.tlt
*********************************************************************/
 
//! \file mosaicSeabedPublisherHLA.h
//! \brief Contains the DtOCEAN2020FOMMosaicSeabedPublisher class declaration.
//! \ingroup OCEAN2020FOM_Environmental
 
#pragma once
 
#if DtHLA
 
#include <vl/objectPublisherHLA.h>
#include "dllExport.h"
 
namespace OCEAN2020 {
 
class DtOCEAN2020FOMMosaicSeabedStateRepository;
 
//! Instances of DtOCEAN2020FOMMosaicSeabedPublisher publish
//! VS_Environment.MosaicSeabed objects to
//! the network.
//! \ingroup OCEAN2020FOM_Environmental
class DT_DLL_OCEAN2020FOM_ENVIRONMENTAL DtOCEAN2020FOMMosaicSeabedPublisher : public DtObjectPublisher
{
public:
   //! Function prototype for a function that creates a DtOCEAN2020FOMMosaicSeabedStateRepository
   typedef DtOCEAN2020FOMMosaicSeabedStateRepository* (*DtStateRepCreator)();
 
public:
   //! Constructor.
   DtOCEAN2020FOMMosaicSeabedPublisher(
      DtOCEAN2020FOMMosaicSeabedStateRepository* stateRepToUse,
      DtExerciseConn* conn,
      const char* name = 0,
      const DtDDMRegionSet* regionSetToUse = 0);
 
   //! Constructor.
   DtOCEAN2020FOMMosaicSeabedPublisher(
      RTI::ObjectClassHandle h,
      DtExerciseConn* conn,
      const char* name = 0,
      const DtDDMRegionSet* regionSetToUse = 0);
 
   //! Constructor.
   DtOCEAN2020FOMMosaicSeabedPublisher(
      DtExerciseConn* conn,
      const char* name = 0,
      const DtDDMRegionSet* regionSetToUse = 0);
 
   //! Constructor that creates a publisher for an existing DtHlaObject.
   //! (DtHlaObjectWithStateRep is derived from DtHlaObject.)  Typically used
   //! in conjunction with ownership management, when you want to take
   //! ownership and begin updating some attributes of an object that you have
   //! already discovered.
   DtOCEAN2020FOMMosaicSeabedPublisher( DtHlaObjectWithStateRep* obj, DtExerciseConn* conn);
 
   //! The Object class name (VS_Environment.MosaicSeabed)
   static const char * objectClassName();
   
   //! Destructor.
   virtual ~DtOCEAN2020FOMMosaicSeabedPublisher();
 
private:
   //! Copy Constructor -- not implemented.
   DtOCEAN2020FOMMosaicSeabedPublisher(const DtOCEAN2020FOMMosaicSeabedPublisher& orig);
 
   //! Assignment operator -- not implemented.
   DtOCEAN2020FOMMosaicSeabedPublisher& operator=(
      const DtOCEAN2020FOMMosaicSeabedPublisher& orig);
 
public:
 
   //! Returns a pointer to the DtOCEAN2020FOMMosaicSeabedStateRepository - through
   //! which you can set or inspect current state information.
   virtual DtOCEAN2020FOMMosaicSeabedStateRepository* mosaicSeabedStateRep();
 
   //! Synonym for mosaicSeabedStateRep().
   virtual DtOCEAN2020FOMMosaicSeabedStateRepository* msr();
 
public:
   //! Give us a function to be used for creating SRs.
   static DtStateRepCreator setStateRepCreator(DtStateRepCreator creator);
 
protected:
   static DtStateRepCreator theStateRepCreator;
};
 
inline DtOCEAN2020FOMMosaicSeabedStateRepository* DtOCEAN2020FOMMosaicSeabedPublisher::mosaicSeabedStateRep()
{
   return (DtOCEAN2020FOMMosaicSeabedStateRepository*) myStateRep;
}
 
inline DtOCEAN2020FOMMosaicSeabedStateRepository* DtOCEAN2020FOMMosaicSeabedPublisher::msr()
{
   return (DtOCEAN2020FOMMosaicSeabedStateRepository*) myStateRep;
}
 
} //end OCEAN2020
 
#endif
