/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hrefObjHeader.tlt
*********************************************************************/
 
//! \file <!HlaRefObj!>.h
//! \brief Contains the DtReflectedOCEAN2020FOMWaterSurface class declaration.
//! \ingroup OCEAN2020FOM_Environmental
 
#pragma once
 
#if DtHLA
 
#include <vl/reflectedObjectHLA.h>
#include "dllExport.h"
#include "waterSurfaceStateRepository.h"
 
namespace OCEAN2020 {
 
class DtReflectedOCEAN2020FOMWaterSurface;
 
//! Signature of the callback function that takes a DtReflectedOCEAN2020FOMWaterSurface
//! and user data
//! \ingroup OCEAN2020FOM_Environmental
typedef void (*DtOCEAN2020FOMWaterSurfaceCallbackFunction)(
   DtReflectedOCEAN2020FOMWaterSurface* obj, void* userData);
 
//! Instances of DtReflectedOCEAN2020FOMWaterSurface are used to represent a
//! simulated HLAobjectRoot.VS_Environment.WaterSurface
//! object reflected across a network. 
//! \ingroup OCEAN2020FOM_Environmental
class DT_DLL_OCEAN2020FOM_ENVIRONMENTAL DtReflectedOCEAN2020FOMWaterSurface : public DtReflectedObject
{
public:
   //! Function prototype for functions that create a
   //! DtOCEAN2020FOMWaterSurfaceStateRepository.
   typedef DtOCEAN2020FOMWaterSurfaceStateRepository* (*DtStateRepCreator)();
 
public:
   //! Constructor.
   DtReflectedOCEAN2020FOMWaterSurface(DtHlaObject* obj, DtExerciseConn* exConn);
 
   //! Destructor.
   virtual ~DtReflectedOCEAN2020FOMWaterSurface();
 
   //! Returns the WaterSurface's state repository.
   virtual DtOCEAN2020FOMWaterSurfaceStateRepository* waterSurfaceStateRep() const;
 
   //! Shorter version of lifeformRep.
   virtual DtOCEAN2020FOMWaterSurfaceStateRepository* wsr() const;
 
   //! Returns the next reflected WaterSurface in the 
   //! DtReflectedOCEAN2020FOMWaterSurfaceList.
   virtual DtReflectedOCEAN2020FOMWaterSurface* next() const;
 
   //! Returns the previous reflected WaterSurface in the 
   //! DtReflectedOCEAN2020FOMWaterSurfaceList.
   virtual DtReflectedOCEAN2020FOMWaterSurface* prev() const;
 
   //! Returns the next reflected WaterSurface. Will cycle back to the first 
   //! remote WaterSurface in the DtReflectedOCEAN2020FOMWaterSurfaceList.
   virtual DtReflectedOCEAN2020FOMWaterSurface* wrapNext() const;
 
   //! Returns the previous reflected WaterSurface. Will cycle back to the first 
   //! remote WaterSurface in the DtReflectedOCEAN2020FOMWaterSurfaceList.
   virtual DtReflectedOCEAN2020FOMWaterSurface* wrapPrev() const;
 
   //! Add a callback that is called when the DtReflectedOCEAN2020FOMWaterSurface is
   //! updated.
   virtual void addPostUpdateCallback(
      DtOCEAN2020FOMWaterSurfaceCallbackFunction cb, void* userData);
 
   //! Remove the callback that is called when the DtReflectedOCEAN2020FOMWaterSurface
   //! is updated.
   virtual void removePostUpdateCallback(
      DtOCEAN2020FOMWaterSurfaceCallbackFunction cb, void* userData);
 
public:
   //! Set the function to be called for creating state repositories.
   static DtStateRepCreator setStateRepCreator(DtStateRepCreator creator);
 
protected:
   //! Copy Constructor not implemented.
   DtReflectedOCEAN2020FOMWaterSurface(const DtReflectedOCEAN2020FOMWaterSurface& orig);
 
   //! Assignment operator not implemented.
   DtReflectedOCEAN2020FOMWaterSurface& operator=(const DtReflectedOCEAN2020FOMWaterSurface& orig);
 
protected:
   //! The function called to create state repositories.
   static DtStateRepCreator theStateRepCreator;
};
 
inline DtOCEAN2020FOMWaterSurfaceStateRepository* DtReflectedOCEAN2020FOMWaterSurface::waterSurfaceStateRep() const
{ 
   return (DtOCEAN2020FOMWaterSurfaceStateRepository*) myStateRep;
}
 
inline DtOCEAN2020FOMWaterSurfaceStateRepository* DtReflectedOCEAN2020FOMWaterSurface::wsr() const
{
   return (DtOCEAN2020FOMWaterSurfaceStateRepository*) myStateRep;
}
 
} //end OCEAN2020
 
#endif
