/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hrefObjHeader.tlt
*********************************************************************/
 
//! \file <!HlaRefObj!>.h
//! \brief Contains the DtReflectedOCEAN2020FOMBathymetry class declaration.
//! \ingroup OCEAN2020FOM_Environmental
 
#pragma once
 
#if DtHLA
 
#include <vl/reflectedObjectHLA.h>
#include "dllExport.h"
#include "bathymetryStateRepository.h"
 
namespace OCEAN2020 {
 
class DtReflectedOCEAN2020FOMBathymetry;
 
//! Signature of the callback function that takes a DtReflectedOCEAN2020FOMBathymetry
//! and user data
//! \ingroup OCEAN2020FOM_Environmental
typedef void (*DtOCEAN2020FOMBathymetryCallbackFunction)(
   DtReflectedOCEAN2020FOMBathymetry* obj, void* userData);
 
//! Instances of DtReflectedOCEAN2020FOMBathymetry are used to represent a
//! simulated HLAobjectRoot.VS_Environment.Bathymetry
//! object reflected across a network. 
//! \ingroup OCEAN2020FOM_Environmental
class DT_DLL_OCEAN2020FOM_ENVIRONMENTAL DtReflectedOCEAN2020FOMBathymetry : public DtReflectedObject
{
public:
   //! Function prototype for functions that create a
   //! DtOCEAN2020FOMBathymetryStateRepository.
   typedef DtOCEAN2020FOMBathymetryStateRepository* (*DtStateRepCreator)();
 
public:
   //! Constructor.
   DtReflectedOCEAN2020FOMBathymetry(DtHlaObject* obj, DtExerciseConn* exConn);
 
   //! Destructor.
   virtual ~DtReflectedOCEAN2020FOMBathymetry();
 
   //! Returns the Bathymetry's state repository.
   virtual DtOCEAN2020FOMBathymetryStateRepository* bathymetryStateRep() const;
 
   //! Shorter version of lifeformRep.
   virtual DtOCEAN2020FOMBathymetryStateRepository* bsr() const;
 
   //! Returns the next reflected Bathymetry in the 
   //! DtReflectedOCEAN2020FOMBathymetryList.
   virtual DtReflectedOCEAN2020FOMBathymetry* next() const;
 
   //! Returns the previous reflected Bathymetry in the 
   //! DtReflectedOCEAN2020FOMBathymetryList.
   virtual DtReflectedOCEAN2020FOMBathymetry* prev() const;
 
   //! Returns the next reflected Bathymetry. Will cycle back to the first 
   //! remote Bathymetry in the DtReflectedOCEAN2020FOMBathymetryList.
   virtual DtReflectedOCEAN2020FOMBathymetry* wrapNext() const;
 
   //! Returns the previous reflected Bathymetry. Will cycle back to the first 
   //! remote Bathymetry in the DtReflectedOCEAN2020FOMBathymetryList.
   virtual DtReflectedOCEAN2020FOMBathymetry* wrapPrev() const;
 
   //! Add a callback that is called when the DtReflectedOCEAN2020FOMBathymetry is
   //! updated.
   virtual void addPostUpdateCallback(
      DtOCEAN2020FOMBathymetryCallbackFunction cb, void* userData);
 
   //! Remove the callback that is called when the DtReflectedOCEAN2020FOMBathymetry
   //! is updated.
   virtual void removePostUpdateCallback(
      DtOCEAN2020FOMBathymetryCallbackFunction cb, void* userData);
 
public:
   //! Set the function to be called for creating state repositories.
   static DtStateRepCreator setStateRepCreator(DtStateRepCreator creator);
 
protected:
   //! Copy Constructor not implemented.
   DtReflectedOCEAN2020FOMBathymetry(const DtReflectedOCEAN2020FOMBathymetry& orig);
 
   //! Assignment operator not implemented.
   DtReflectedOCEAN2020FOMBathymetry& operator=(const DtReflectedOCEAN2020FOMBathymetry& orig);
 
protected:
   //! The function called to create state repositories.
   static DtStateRepCreator theStateRepCreator;
};
 
inline DtOCEAN2020FOMBathymetryStateRepository* DtReflectedOCEAN2020FOMBathymetry::bathymetryStateRep() const
{ 
   return (DtOCEAN2020FOMBathymetryStateRepository*) myStateRep;
}
 
inline DtOCEAN2020FOMBathymetryStateRepository* DtReflectedOCEAN2020FOMBathymetry::bsr() const
{
   return (DtOCEAN2020FOMBathymetryStateRepository*) myStateRep;
}
 
} //end OCEAN2020
 
#endif
