/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hrefObjHeader.tlt
*********************************************************************/
 
//! \file <!HlaRefObj!>.h
//! \brief Contains the DtReflectedOCEAN2020FOMAirColumn class declaration.
//! \ingroup OCEAN2020FOM_Environmental
 
#pragma once
 
#if DtHLA
 
#include <vl/reflectedObjectHLA.h>
#include "dllExport.h"
#include "airColumnStateRepository.h"
 
namespace OCEAN2020 {
 
class DtReflectedOCEAN2020FOMAirColumn;
 
//! Signature of the callback function that takes a DtReflectedOCEAN2020FOMAirColumn
//! and user data
//! \ingroup OCEAN2020FOM_Environmental
typedef void (*DtOCEAN2020FOMAirColumnCallbackFunction)(
   DtReflectedOCEAN2020FOMAirColumn* obj, void* userData);
 
//! Instances of DtReflectedOCEAN2020FOMAirColumn are used to represent a
//! simulated HLAobjectRoot.VS_Environment.AirColumn
//! object reflected across a network. 
//! \ingroup OCEAN2020FOM_Environmental
class DT_DLL_OCEAN2020FOM_ENVIRONMENTAL DtReflectedOCEAN2020FOMAirColumn : public DtReflectedObject
{
public:
   //! Function prototype for functions that create a
   //! DtOCEAN2020FOMAirColumnStateRepository.
   typedef DtOCEAN2020FOMAirColumnStateRepository* (*DtStateRepCreator)();
 
public:
   //! Constructor.
   DtReflectedOCEAN2020FOMAirColumn(DtHlaObject* obj, DtExerciseConn* exConn);
 
   //! Destructor.
   virtual ~DtReflectedOCEAN2020FOMAirColumn();
 
   //! Returns the AirColumn's state repository.
   virtual DtOCEAN2020FOMAirColumnStateRepository* airColumnStateRep() const;
 
   //! Shorter version of lifeformRep.
   virtual DtOCEAN2020FOMAirColumnStateRepository* asr() const;
 
   //! Returns the next reflected AirColumn in the 
   //! DtReflectedOCEAN2020FOMAirColumnList.
   virtual DtReflectedOCEAN2020FOMAirColumn* next() const;
 
   //! Returns the previous reflected AirColumn in the 
   //! DtReflectedOCEAN2020FOMAirColumnList.
   virtual DtReflectedOCEAN2020FOMAirColumn* prev() const;
 
   //! Returns the next reflected AirColumn. Will cycle back to the first 
   //! remote AirColumn in the DtReflectedOCEAN2020FOMAirColumnList.
   virtual DtReflectedOCEAN2020FOMAirColumn* wrapNext() const;
 
   //! Returns the previous reflected AirColumn. Will cycle back to the first 
   //! remote AirColumn in the DtReflectedOCEAN2020FOMAirColumnList.
   virtual DtReflectedOCEAN2020FOMAirColumn* wrapPrev() const;
 
   //! Add a callback that is called when the DtReflectedOCEAN2020FOMAirColumn is
   //! updated.
   virtual void addPostUpdateCallback(
      DtOCEAN2020FOMAirColumnCallbackFunction cb, void* userData);
 
   //! Remove the callback that is called when the DtReflectedOCEAN2020FOMAirColumn
   //! is updated.
   virtual void removePostUpdateCallback(
      DtOCEAN2020FOMAirColumnCallbackFunction cb, void* userData);
 
public:
   //! Set the function to be called for creating state repositories.
   static DtStateRepCreator setStateRepCreator(DtStateRepCreator creator);
 
protected:
   //! Copy Constructor not implemented.
   DtReflectedOCEAN2020FOMAirColumn(const DtReflectedOCEAN2020FOMAirColumn& orig);
 
   //! Assignment operator not implemented.
   DtReflectedOCEAN2020FOMAirColumn& operator=(const DtReflectedOCEAN2020FOMAirColumn& orig);
 
protected:
   //! The function called to create state repositories.
   static DtStateRepCreator theStateRepCreator;
};
 
inline DtOCEAN2020FOMAirColumnStateRepository* DtReflectedOCEAN2020FOMAirColumn::airColumnStateRep() const
{ 
   return (DtOCEAN2020FOMAirColumnStateRepository*) myStateRep;
}
 
inline DtOCEAN2020FOMAirColumnStateRepository* DtReflectedOCEAN2020FOMAirColumn::asr() const
{
   return (DtOCEAN2020FOMAirColumnStateRepository*) myStateRep;
}
 
} //end OCEAN2020
 
#endif
