/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hrefListHeader.tlt
*********************************************************************/
 
//! \file reflectedVS_EnvironmentListHLA.h
//! \brief Contains the DtReflectedOCEAN2020FOMVS_EnvironmentList class declaration.
//! \ingroup OCEAN2020FOM_Environmental
 
#pragma once
 
#if DtHLA
 
#include "dllExport.h"
#include <vl/reflectedObjectListHLA.h>
#include "reflectedVS_EnvironmentHLA.h"
 
namespace OCEAN2020 {
 
//! Instances of DtReflectedOCEAN2020FOMVS_EnvironmentList manage a list of
//! DtReflectedOCEAN2020FOMVS_Environment objects.
//! \ingroup OCEAN2020FOM_Environmental
class DT_DLL_OCEAN2020FOM_ENVIRONMENTAL DtReflectedOCEAN2020FOMVS_EnvironmentList : public DtReflectedObjectList
{
public:
   //! Constructor. 
   DtReflectedOCEAN2020FOMVS_EnvironmentList(DtExerciseConn* exConn,
      const DtDDMRegionSet* regionSetToUse = 0);
 
   //! Constructor - only subscribe to the RTI::ObjectClassHandles
   //! in handleList.
   DtReflectedOCEAN2020FOMVS_EnvironmentList(DtExerciseConn* exConn,
      const DtList *handleList, const DtDDMRegionSet* regionSetToUse = 0);
 
   //! Destructor.
   virtual ~DtReflectedOCEAN2020FOMVS_EnvironmentList();
 
private:
 
   //! Copy constructor not implemented - cannot be copied.
   DtReflectedOCEAN2020FOMVS_EnvironmentList(const DtReflectedOCEAN2020FOMVS_EnvironmentList& orig);
 
   //! Assignment operator not implemented - cannot be copied.
   DtReflectedOCEAN2020FOMVS_EnvironmentList& operator=(const DtReflectedOCEAN2020FOMVS_EnvironmentList&orig);
 
public:
 
   //! Look up by identifier.
   virtual DtReflectedOCEAN2020FOMVS_Environment* lookup(
#if DtHLA_1516
      RTI::ObjectInstanceHandle id);
#else
      RTI::ObjectHandle id);
#endif
 
   //! Look up by name.
   virtual DtReflectedOCEAN2020FOMVS_Environment* lookup(
      const DtGlobalObjectDesignator& objName);
 
   //! Get the first reflected object in the list.
   virtual DtReflectedOCEAN2020FOMVS_Environment* first() const;
 
   //! Get the last reflected object in the list.
   virtual DtReflectedOCEAN2020FOMVS_Environment* last() const;
 
   //! VS_Environment added callback registration
   virtual void addVS_EnvironmentAdditionCallback(
      DtOCEAN2020FOMVS_EnvironmentCallbackFunction cb, void* userData);
 
   //! VS_Environment added callback deregistration
   virtual void removeVS_EnvironmentAdditionCallback(
      DtOCEAN2020FOMVS_EnvironmentCallbackFunction cb, void* userData);
 
   //! VS_Environment removed callback registration
   virtual void addVS_EnvironmentRemovalCallback(
      DtOCEAN2020FOMVS_EnvironmentCallbackFunction cb, void* userData);
 
   //! VS_Environment removed callback deregistration
   virtual void removeVS_EnvironmentRemovalCallback(
      DtOCEAN2020FOMVS_EnvironmentCallbackFunction cb, void* userData);
 
protected:
 
   //! Override of virtual function.  Here, we create a DtReflectedOCEAN2020FOMVS_Environment
   virtual DtReflectedObject* newReflectedObject(DtHlaObject* obj) const;
 
   //! Called from processDiscoverObject() after a remote VS_Environment has
   //! been added to the list.  Default implementation prints a message.
   //! Subclasses can override this function to add functionality on
   //! addition.  obj will be an instance of a class derived from DtReflectedObj.
   virtual void objectAdded(DtReflectedObject* obj);
 
};
 
} //end OCEAN2020
 
#endif
