/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hrefObjHeader.tlt
*********************************************************************/
 
//! \file <!HlaRefObj!>.h
//! \brief Contains the DtReflectedOCEAN2020FOMLand class declaration.
//! \ingroup OCEAN2020FOM_Environmental
 
#pragma once
 
#if DtHLA
 
#include <vl/reflectedObjectHLA.h>
#include "dllExport.h"
#include "landStateRepository.h"
 
namespace OCEAN2020 {
 
class DtReflectedOCEAN2020FOMLand;
 
//! Signature of the callback function that takes a DtReflectedOCEAN2020FOMLand
//! and user data
//! \ingroup OCEAN2020FOM_Environmental
typedef void (*DtOCEAN2020FOMLandCallbackFunction)(
   DtReflectedOCEAN2020FOMLand* obj, void* userData);
 
//! Instances of DtReflectedOCEAN2020FOMLand are used to represent a
//! simulated HLAobjectRoot.VS_Environment.Land
//! object reflected across a network. 
//! \ingroup OCEAN2020FOM_Environmental
class DT_DLL_OCEAN2020FOM_ENVIRONMENTAL DtReflectedOCEAN2020FOMLand : public DtReflectedObject
{
public:
   //! Function prototype for functions that create a
   //! DtOCEAN2020FOMLandStateRepository.
   typedef DtOCEAN2020FOMLandStateRepository* (*DtStateRepCreator)();
 
public:
   //! Constructor.
   DtReflectedOCEAN2020FOMLand(DtHlaObject* obj, DtExerciseConn* exConn);
 
   //! Destructor.
   virtual ~DtReflectedOCEAN2020FOMLand();
 
   //! Returns the Land's state repository.
   virtual DtOCEAN2020FOMLandStateRepository* landStateRep() const;
 
   //! Shorter version of lifeformRep.
   virtual DtOCEAN2020FOMLandStateRepository* lsr() const;
 
   //! Returns the next reflected Land in the 
   //! DtReflectedOCEAN2020FOMLandList.
   virtual DtReflectedOCEAN2020FOMLand* next() const;
 
   //! Returns the previous reflected Land in the 
   //! DtReflectedOCEAN2020FOMLandList.
   virtual DtReflectedOCEAN2020FOMLand* prev() const;
 
   //! Returns the next reflected Land. Will cycle back to the first 
   //! remote Land in the DtReflectedOCEAN2020FOMLandList.
   virtual DtReflectedOCEAN2020FOMLand* wrapNext() const;
 
   //! Returns the previous reflected Land. Will cycle back to the first 
   //! remote Land in the DtReflectedOCEAN2020FOMLandList.
   virtual DtReflectedOCEAN2020FOMLand* wrapPrev() const;
 
   //! Add a callback that is called when the DtReflectedOCEAN2020FOMLand is
   //! updated.
   virtual void addPostUpdateCallback(
      DtOCEAN2020FOMLandCallbackFunction cb, void* userData);
 
   //! Remove the callback that is called when the DtReflectedOCEAN2020FOMLand
   //! is updated.
   virtual void removePostUpdateCallback(
      DtOCEAN2020FOMLandCallbackFunction cb, void* userData);
 
public:
   //! Set the function to be called for creating state repositories.
   static DtStateRepCreator setStateRepCreator(DtStateRepCreator creator);
 
protected:
   //! Copy Constructor not implemented.
   DtReflectedOCEAN2020FOMLand(const DtReflectedOCEAN2020FOMLand& orig);
 
   //! Assignment operator not implemented.
   DtReflectedOCEAN2020FOMLand& operator=(const DtReflectedOCEAN2020FOMLand& orig);
 
protected:
   //! The function called to create state repositories.
   static DtStateRepCreator theStateRepCreator;
};
 
inline DtOCEAN2020FOMLandStateRepository* DtReflectedOCEAN2020FOMLand::landStateRep() const
{ 
   return (DtOCEAN2020FOMLandStateRepository*) myStateRep;
}
 
inline DtOCEAN2020FOMLandStateRepository* DtReflectedOCEAN2020FOMLand::lsr() const
{
   return (DtOCEAN2020FOMLandStateRepository*) myStateRep;
}
 
} //end OCEAN2020
 
#endif
