/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hrefListHeader.tlt
*********************************************************************/
 
//! \file reflectedMosaicSeabedListHLA.h
//! \brief Contains the DtReflectedOCEAN2020FOMMosaicSeabedList class declaration.
//! \ingroup OCEAN2020FOM_Environmental
 
#pragma once
 
#if DtHLA
 
#include "dllExport.h"
#include <vl/reflectedObjectListHLA.h>
#include "reflectedMosaicSeabedHLA.h"
 
namespace OCEAN2020 {
 
//! Instances of DtReflectedOCEAN2020FOMMosaicSeabedList manage a list of
//! DtReflectedOCEAN2020FOMMosaicSeabed objects.
//! \ingroup OCEAN2020FOM_Environmental
class DT_DLL_OCEAN2020FOM_ENVIRONMENTAL DtReflectedOCEAN2020FOMMosaicSeabedList : public DtReflectedObjectList
{
public:
   //! Constructor. 
   DtReflectedOCEAN2020FOMMosaicSeabedList(DtExerciseConn* exConn,
      const DtDDMRegionSet* regionSetToUse = 0);
 
   //! Constructor - only subscribe to the RTI::ObjectClassHandles
   //! in handleList.
   DtReflectedOCEAN2020FOMMosaicSeabedList(DtExerciseConn* exConn,
      const DtList *handleList, const DtDDMRegionSet* regionSetToUse = 0);
 
   //! Destructor.
   virtual ~DtReflectedOCEAN2020FOMMosaicSeabedList();
 
private:
 
   //! Copy constructor not implemented - cannot be copied.
   DtReflectedOCEAN2020FOMMosaicSeabedList(const DtReflectedOCEAN2020FOMMosaicSeabedList& orig);
 
   //! Assignment operator not implemented - cannot be copied.
   DtReflectedOCEAN2020FOMMosaicSeabedList& operator=(const DtReflectedOCEAN2020FOMMosaicSeabedList&orig);
 
public:
 
   //! Look up by identifier.
   virtual DtReflectedOCEAN2020FOMMosaicSeabed* lookup(
#if DtHLA_1516
      RTI::ObjectInstanceHandle id);
#else
      RTI::ObjectHandle id);
#endif
 
   //! Look up by name.
   virtual DtReflectedOCEAN2020FOMMosaicSeabed* lookup(
      const DtGlobalObjectDesignator& objName);
 
   //! Get the first reflected object in the list.
   virtual DtReflectedOCEAN2020FOMMosaicSeabed* first() const;
 
   //! Get the last reflected object in the list.
   virtual DtReflectedOCEAN2020FOMMosaicSeabed* last() const;
 
   //! MosaicSeabed added callback registration
   virtual void addMosaicSeabedAdditionCallback(
      DtOCEAN2020FOMMosaicSeabedCallbackFunction cb, void* userData);
 
   //! MosaicSeabed added callback deregistration
   virtual void removeMosaicSeabedAdditionCallback(
      DtOCEAN2020FOMMosaicSeabedCallbackFunction cb, void* userData);
 
   //! MosaicSeabed removed callback registration
   virtual void addMosaicSeabedRemovalCallback(
      DtOCEAN2020FOMMosaicSeabedCallbackFunction cb, void* userData);
 
   //! MosaicSeabed removed callback deregistration
   virtual void removeMosaicSeabedRemovalCallback(
      DtOCEAN2020FOMMosaicSeabedCallbackFunction cb, void* userData);
 
protected:
 
   //! Override of virtual function.  Here, we create a DtReflectedOCEAN2020FOMMosaicSeabed
   virtual DtReflectedObject* newReflectedObject(DtHlaObject* obj) const;
 
   //! Called from processDiscoverObject() after a remote MosaicSeabed has
   //! been added to the list.  Default implementation prints a message.
   //! Subclasses can override this function to add functionality on
   //! addition.  obj will be an instance of a class derived from DtReflectedObj.
   virtual void objectAdded(DtReflectedObject* obj);
 
};
 
} //end OCEAN2020
 
#endif
