/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hobjEncHeader.tlt
*********************************************************************/
 
//! \file waterColumnEncoderHLA.h
//! \brief Contains the DtOCEAN2020FOMWaterColumnEncoder class declaration.
 
#pragma once
 
#if DtHLA
 
#include "VS_EnvironmentEncoderHLA.h"
#include "dllExport.h"
 
namespace OCEAN2020 {
 
class DtOCEAN2020FOMWaterColumnStateRepository;
 
//! Instances of DtOCEAN2020FOMWaterColumnEncoder encode data
//! from DtOCEAN2020FOMWaterColumnStateRepository objects to the net
//! structures to be sent to the network.
//! \ingroup OCEAN2020FOM_Environmental
class DT_DLL_OCEAN2020FOM_ENVIRONMENTAL DtOCEAN2020FOMWaterColumnEncoder : public DtOCEAN2020FOMVS_EnvironmentEncoder
{
public:
 
   //! Default constructor.
   DtOCEAN2020FOMWaterColumnEncoder(
      DtExerciseConn* exConn,
      DtObjClassDesc* classDesc);
 
   //! Destructor.
   virtual ~DtOCEAN2020FOMWaterColumnEncoder();
 
   //! Copy constructor.
   DtOCEAN2020FOMWaterColumnEncoder(const DtOCEAN2020FOMWaterColumnEncoder& orig);
 
   //! Assignment operator.
   DtOCEAN2020FOMWaterColumnEncoder& operator=(const DtOCEAN2020FOMWaterColumnEncoder& orig);
 
public:
   //! Function that creates a DtOCEAN2020FOMWaterColumnEncoder.
   static DtHlaStateEncoder* create(
      DtExerciseConn* exConn,
      DtObjClassDesc* classDesc);
   
protected:

   //! Return true if NumberOfLayers needs to be sent
   //! to the network, false otherwise.
   static bool needNumberOfLayers(
      const DtOCEAN2020FOMWaterColumnStateRepository& stateRep, 
      const DtOCEAN2020FOMWaterColumnStateRepository& asSeenByRemote);
 
   //! Encodes NumberOfLayers from rep into attrs.
   static void encodeNumberOfLayers(
      const DtOCEAN2020FOMWaterColumnStateRepository& rep,
      RTI::AttributeHandleValuePairSet* attrs,
      RTI::AttributeHandle attrHandle);

   //! Return true if WaterDepth needs to be sent
   //! to the network, false otherwise.
   static bool needWaterDepth(
      const DtOCEAN2020FOMWaterColumnStateRepository& stateRep, 
      const DtOCEAN2020FOMWaterColumnStateRepository& asSeenByRemote);
 
   //! Encodes WaterDepth from rep into attrs.
   static void encodeWaterDepth(
      const DtOCEAN2020FOMWaterColumnStateRepository& rep,
      RTI::AttributeHandleValuePairSet* attrs,
      RTI::AttributeHandle attrHandle);

   //! Return true if ShallowerLayer needs to be sent
   //! to the network, false otherwise.
   static bool needShallowerLayer(
      const DtOCEAN2020FOMWaterColumnStateRepository& stateRep, 
      const DtOCEAN2020FOMWaterColumnStateRepository& asSeenByRemote);
 
   //! Encodes ShallowerLayer from rep into attrs.
   static void encodeShallowerLayer(
      const DtOCEAN2020FOMWaterColumnStateRepository& rep,
      RTI::AttributeHandleValuePairSet* attrs,
      RTI::AttributeHandle attrHandle);

   //! Return true if DeeperLayer needs to be sent
   //! to the network, false otherwise.
   static bool needDeeperLayer(
      const DtOCEAN2020FOMWaterColumnStateRepository& stateRep, 
      const DtOCEAN2020FOMWaterColumnStateRepository& asSeenByRemote);
 
   //! Encodes DeeperLayer from rep into attrs.
   static void encodeDeeperLayer(
      const DtOCEAN2020FOMWaterColumnStateRepository& rep,
      RTI::AttributeHandleValuePairSet* attrs,
      RTI::AttributeHandle attrHandle);

   //! Return true if Current_intensity needs to be sent
   //! to the network, false otherwise.
   static bool needCurrent_intensity(
      const DtOCEAN2020FOMWaterColumnStateRepository& stateRep, 
      const DtOCEAN2020FOMWaterColumnStateRepository& asSeenByRemote);
 
   //! Encodes Current_intensity from rep into attrs.
   static void encodeCurrent_intensity(
      const DtOCEAN2020FOMWaterColumnStateRepository& rep,
      RTI::AttributeHandleValuePairSet* attrs,
      RTI::AttributeHandle attrHandle);

   //! Return true if Current_direction needs to be sent
   //! to the network, false otherwise.
   static bool needCurrent_direction(
      const DtOCEAN2020FOMWaterColumnStateRepository& stateRep, 
      const DtOCEAN2020FOMWaterColumnStateRepository& asSeenByRemote);
 
   //! Encodes Current_direction from rep into attrs.
   static void encodeCurrent_direction(
      const DtOCEAN2020FOMWaterColumnStateRepository& rep,
      RTI::AttributeHandleValuePairSet* attrs,
      RTI::AttributeHandle attrHandle);

   //! Return true if Salinity needs to be sent
   //! to the network, false otherwise.
   static bool needSalinity(
      const DtOCEAN2020FOMWaterColumnStateRepository& stateRep, 
      const DtOCEAN2020FOMWaterColumnStateRepository& asSeenByRemote);
 
   //! Encodes Salinity from rep into attrs.
   static void encodeSalinity(
      const DtOCEAN2020FOMWaterColumnStateRepository& rep,
      RTI::AttributeHandleValuePairSet* attrs,
      RTI::AttributeHandle attrHandle);

   //! Return true if Temperature needs to be sent
   //! to the network, false otherwise.
   static bool needTemperature(
      const DtOCEAN2020FOMWaterColumnStateRepository& stateRep, 
      const DtOCEAN2020FOMWaterColumnStateRepository& asSeenByRemote);
 
   //! Encodes Temperature from rep into attrs.
   static void encodeTemperature(
      const DtOCEAN2020FOMWaterColumnStateRepository& rep,
      RTI::AttributeHandleValuePairSet* attrs,
      RTI::AttributeHandle attrHandle);

   //! Return true if Transparency needs to be sent
   //! to the network, false otherwise.
   static bool needTransparency(
      const DtOCEAN2020FOMWaterColumnStateRepository& stateRep, 
      const DtOCEAN2020FOMWaterColumnStateRepository& asSeenByRemote);
 
   //! Encodes Transparency from rep into attrs.
   static void encodeTransparency(
      const DtOCEAN2020FOMWaterColumnStateRepository& rep,
      RTI::AttributeHandleValuePairSet* attrs,
      RTI::AttributeHandle attrHandle);

};
 
} //end OCEAN2020
 
#endif
