/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hpubHeader.tlt
*********************************************************************/
 
//! \file waterSurfacePublisherHLA.h
//! \brief Contains the DtOCEAN2020FOMWaterSurfacePublisher class declaration.
//! \ingroup OCEAN2020FOM_Environmental
 
#pragma once
 
#if DtHLA
 
#include <vl/objectPublisherHLA.h>
#include "dllExport.h"
 
namespace OCEAN2020 {
 
class DtOCEAN2020FOMWaterSurfaceStateRepository;
 
//! Instances of DtOCEAN2020FOMWaterSurfacePublisher publish
//! VS_Environment.WaterSurface objects to
//! the network.
//! \ingroup OCEAN2020FOM_Environmental
class DT_DLL_OCEAN2020FOM_ENVIRONMENTAL DtOCEAN2020FOMWaterSurfacePublisher : public DtObjectPublisher
{
public:
   //! Function prototype for a function that creates a DtOCEAN2020FOMWaterSurfaceStateRepository
   typedef DtOCEAN2020FOMWaterSurfaceStateRepository* (*DtStateRepCreator)();
 
public:
   //! Constructor.
   DtOCEAN2020FOMWaterSurfacePublisher(
      DtOCEAN2020FOMWaterSurfaceStateRepository* stateRepToUse,
      DtExerciseConn* conn,
      const char* name = 0,
      const DtDDMRegionSet* regionSetToUse = 0);
 
   //! Constructor.
   DtOCEAN2020FOMWaterSurfacePublisher(
      RTI::ObjectClassHandle h,
      DtExerciseConn* conn,
      const char* name = 0,
      const DtDDMRegionSet* regionSetToUse = 0);
 
   //! Constructor.
   DtOCEAN2020FOMWaterSurfacePublisher(
      DtExerciseConn* conn,
      const char* name = 0,
      const DtDDMRegionSet* regionSetToUse = 0);
 
   //! Constructor that creates a publisher for an existing DtHlaObject.
   //! (DtHlaObjectWithStateRep is derived from DtHlaObject.)  Typically used
   //! in conjunction with ownership management, when you want to take
   //! ownership and begin updating some attributes of an object that you have
   //! already discovered.
   DtOCEAN2020FOMWaterSurfacePublisher( DtHlaObjectWithStateRep* obj, DtExerciseConn* conn);
 
   //! The Object class name (VS_Environment.WaterSurface)
   static const char * objectClassName();
   
   //! Destructor.
   virtual ~DtOCEAN2020FOMWaterSurfacePublisher();
 
private:
   //! Copy Constructor -- not implemented.
   DtOCEAN2020FOMWaterSurfacePublisher(const DtOCEAN2020FOMWaterSurfacePublisher& orig);
 
   //! Assignment operator -- not implemented.
   DtOCEAN2020FOMWaterSurfacePublisher& operator=(
      const DtOCEAN2020FOMWaterSurfacePublisher& orig);
 
public:
 
   //! Returns a pointer to the DtOCEAN2020FOMWaterSurfaceStateRepository - through
   //! which you can set or inspect current state information.
   virtual DtOCEAN2020FOMWaterSurfaceStateRepository* waterSurfaceStateRep();
 
   //! Synonym for waterSurfaceStateRep().
   virtual DtOCEAN2020FOMWaterSurfaceStateRepository* wsr();
 
public:
   //! Give us a function to be used for creating SRs.
   static DtStateRepCreator setStateRepCreator(DtStateRepCreator creator);
 
protected:
   static DtStateRepCreator theStateRepCreator;
};
 
inline DtOCEAN2020FOMWaterSurfaceStateRepository* DtOCEAN2020FOMWaterSurfacePublisher::waterSurfaceStateRep()
{
   return (DtOCEAN2020FOMWaterSurfaceStateRepository*) myStateRep;
}
 
inline DtOCEAN2020FOMWaterSurfaceStateRepository* DtOCEAN2020FOMWaterSurfacePublisher::wsr()
{
   return (DtOCEAN2020FOMWaterSurfaceStateRepository*) myStateRep;
}
 
} //end OCEAN2020
 
#endif
