/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**enums.tlt
*********************************************************************/
 
#pragma once
 

