#pragma once
#ifndef DATA_CONSTANT_VALUES_H
#define DATA_CONSTANT_VALUES_H


#define PI 3.14159265358979
#define GRAVITY 9.80665
#define C_VELOCITY 299792458
#define EARTH_RADIUS_M 6371000

#define NO_ELEMENT		0
#define AIRCOLUMN		1
#define LAND			2
#define WATERCOLUMN		4
#define WATERSURFACE	8

enum COLOR_TEXT {
	MAIN_TITLE_BLUE = 16,
	MAIN_TITLE_GREEN = 32,
	MAIN_TITLE_CYAN = 48,
	MAIN_TITLE_RED = 64,
	MAIN_TITLE_YELLOW = 96,
	MAIN_TITLE_GRAY = 128,
	BLUE_COLOR = 1,
	RED_COLOR = 4,
	ORANGE_COLOR = 6,
	GRAY_COLOR = 8,
	GREEN_COLOR = 10,
	CYAN_COLOR = 11,
	YELLOW_COLOR = 15
};

enum VESSEL_STATUS {
	ACTIVE = 'A',
	DESTROYED = 'D',
	ERROR_VESSEL = 'E',
	IMMOBILZED = 'I'
};

enum EVENT_MESSAGE {
	TARGET_INCOMING = 0,
	TASK_EXECUTION = 1,
	NO_MESSAGE = 2,
	RESET_VESSELS = 3,
	ERROR_EVENT = 4,
	STOP
};

enum JOB {
	PATROLING = 'P',
	VANGUARED = 'V',
	RESET = 'R',
	INSPECTION = 'I',
	SHADOWING = 'S',
	LOCK = 'L',
	OVERSIGHT = 'O',
	RECOVERY = 'C',
	NONE = 'N'
};

enum MODE {
	LOITER_SURVEILANCE = 'L',
	TRACKING_SHADOWING = 'T'
};

#endif