/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**enums.tlt
*********************************************************************/
 
#pragma once
 

enum DtSensorMode
{
   DtSensorMode_COLOR = 0,
   DtSensorMode_IR = 1,
   DtSensorMode_MONOCHROME = 2,
   DtSensorMode_NVG = 3,
   DtMaxDtSensorMode
};
 

